courses/urls.py
from django.conf.urls import url
from .views import (CourseListView,
                    CourseDetailView,
                    LectureDetailView,
                    CourseCreateView,
                    CourseUpdateView,
                    CourseDeleteView,
                    CoursePurchaseView)

urlpatterns = [

    url(r'^$', CourseListView.as_view(), name='list'),
    url(r'^create/$', CourseCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', CourseDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/purchase/$', CoursePurchaseView.as_view(), name='purchase'),
    url(r'^(?P<cslug>[\w-]+)/(?P<lslug>[\w-]+)$', LectureDetailView.as_view(), name='lecture-detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', CourseUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', CourseDeleteView.as_view(), name='delete'),
]

eswahiligigs/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from .views import HomePageView, HomeStagePageView, login_after_password_change, MainPageView, DashboardPageView, \
    AccountPageView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePageView.as_view(), name='landing'),
    url(r'^main/$', MainPageView.as_view(), name='main'),
    url(r'^dashboard/account/user/$', AccountPageView.as_view(), name='account_dashboard'),
    url(r'^dashboard/$', DashboardPageView.as_view(), name='dashboard'),
    url(r'^accounts/password/change/$', login_after_password_change,
        name='account_change_password'),
    url('accounts/', include('allauth.urls')),
    url(r'^home/$', HomeStagePageView.as_view(), name='home'),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^videos/', include('videos.urls', namespace='videos')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^payments/', include('billing.urls', namespace='payments')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^api/comments/', include('comments.api.urls', namespace='api_comments')),
    url(r'^eswahiligigs/messages/', include('messages_eswahili.urls', namespace='eswahiligigs_messages')),
    url(r'^questions/', include('questions.urls', namespace='questions')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/urls.py
from django.conf.urls import url
from .views import SearchView

urlpatterns = [
    url(r'^$', SearchView.as_view(), name='default'),

]

courses/models.py
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models
from django.db.models import Prefetch, Q
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from .utils import create_slug, make_display_price
from videos.models import Video
from .fields import PositionField
from categories.models import Category


# Create your models here.
class MyCourses(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    courses = models.ManyToManyField('Course', related_name='owned', blank=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.courses.all().count())

    class Meta:
        verbose_name = 'My courses'
        verbose_name_plural = 'My courses'


def post_save_user_create(sender, instance, created, *args, **kwargs):
    if created:
        MyCourses.objects.get_or_create(user=instance)


post_save.connect(post_save_user_create, sender=settings.AUTH_USER_MODEL)

POS_CHOICES = (('main', 'Main'), ('sec', 'Secondary'))


class CourseQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def lectures(self):
        return self.prefetch_related('lecture_set')

    def featured(self):
        return self.filter(Q(category__slug='featured'))

    def owned(self, user):
        if user.is_authenticated():
            qs = MyCourses.objects.filter(user=user)
        else:
            qs = MyCourses.objects.none()

        return self.prefetch_related(
            Prefetch('owned', queryset=qs, to_attr='is_owner'))


class CourseManager(models.Manager):
    def get_queryset(self):
        return CourseQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().all().active()


def handle_upload(instance, filename):
    if instance.slug:
        return "%s/images/%s" % (instance.slug, filename)
    return "%s/unknown/images/%s" % (filename)


class Course(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=120)
    # category = models.CharField(max_length=120, choices=POS_CHOICES, default='main')
    image = models.ImageField(upload_to=handle_upload, height_field='image_height', width_field='image_width',
                              blank=True, null=True)
    image_height = models.IntegerField(blank=True, null=True)
    image_width = models.IntegerField(blank=True, null=True)
    category = models.ForeignKey(Category, related_name='primary_category', null=True, blank=True)
    secondary = models.ManyToManyField(Category, related_name='secondary_category', blank=True)
    order = PositionField(collection='category')
    slug = models.SlugField(blank=True)
    active = models.BooleanField(default=True)
    price = models.DecimalField(decimal_places=2, max_digits=20, blank=True, null=True)
    description = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CourseManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'slug': self.slug})

    def get_purchase_url(self):
        return reverse('courses:purchase', kwargs={'slug': self.slug})

    def display_price(self):
        return make_display_price(self.price)


def post_save_course_receiver(sender, instance, created, *args, **kwargs):
    if not instance.category in instance.secondary.all():
        instance.secondary.add(instance.category)


post_save.connect(post_save_course_receiver, sender=Course)


class Lecture(models.Model):
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    video = models.ForeignKey(Video, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=120)
    order = PositionField(collection='course')
    slug = models.SlugField(blank=True)
    free = models.BooleanField(default=False)
    description = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('slug', 'course'),)
        ordering = ['order', 'title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:lecture-detail',
                       kwargs={
                           'cslug': self.course.slug,
                           'lslug': self.slug,
                       })


def pre_save_video_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_video_receiver, sender=Course)

# pre_save.connect(pre_save_video_receiver, sender=Lecture)

courses/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Course, Lecture
from videos.models import Video


class LectureAdminForm(forms.ModelForm):
    class Meta:
        model = Lecture
        fields = ['free', 'order', 'title', 'video', 'description', 'slug']

    def __init__(self, *args, **kwargs):
        super(LectureAdminForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['free'].widget.attrs['class'] = 'form-control'
        self.fields['order'].widget.attrs['class'] = 'form-control'
        self.fields['video'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['slug'].widget.attrs['class'] = 'form-control'
        obj = kwargs.get("instance")
        qs = Video.objects.all().unused()
        if obj:
            if obj.video:
                this_ = Video.objects.filter(pk=obj.video.pk)
                qs = (qs | this_)
            self.fields['video'].queryset = qs
        else:
            self.fields['video'].queryset = qs


class CourseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['category'].widget.attrs['class'] = 'form-control'
        self.fields['secondary'].widget.attrs['class'] = 'form-control'
        self.fields['image'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Course
        fields = ['title', 'description', 'category', 'secondary', 'image']
        exclude = ()

CourseFormSet= forms.modelformset_factory(Course,form=CourseForm,extra=1)
CourseLectureFormSet = inlineformset_factory(Course,Lecture, form=LectureAdminForm, formset=CourseFormSet, extra=1)

courses/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.http import Http404
from django.views.generic import (CreateView,
                                  DetailView,
                                  ListView,
                                  UpdateView,
                                  DeleteView,
                                  RedirectView,
                                  View)
from .models import Course, Lecture, MyCourses
from .forms import CourseForm, CourseLectureFormSet
from videos.mixins import MemberRequiredMixin, StaffRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from analytics.models import CourseViewEvent


# Create your views here.
class CourseCreateView(StaffRequiredMixin, CreateView):
    model = Course
    form_class = CourseForm

    # def get_context_data(self, **kwargs):
    #     data = super(CourseCreateView, self).get_context_data(**kwargs)
    #     if self.request.POST:
    #         data['lecture'] = CourseLectureFormSet(self.request.POST)
    #     else:
    #         data['lecture'] = CourseLectureFormSet()
    #     return data

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super(CourseCreateView, self).form_valid(form)


class LectureDetailView(View):
    def get(self, request, cslug, lslug, *args, **kwargs):
        obj = None
        qs = Course.objects.filter(slug=cslug).lectures().owned(request.user)
        if not qs.exists():
            raise Http404
        course_ = qs.first()
        if request.user.is_authenticated():
            view_event, created = CourseViewEvent.objects.get_or_create(user=request.user, course=course_)
            if view_event:
                view_event.views += 1
                view_event.save()

        lectures_qs = course_.lecture_set.filter(slug=lslug)
        if not lectures_qs.exists():
            raise Http404
        obj = lectures_qs.first()
        context = {
            'object': obj,
            'course_': course_
        }
        if not course_.is_owner and not obj.free:
            return render(request, "courses/must_purchase.html", {"object": course_})
        return render(request, 'courses/lecture_detail.html', context)


class CourseDetailView(DetailView):
    queryset = Course.objects.all()

    def get_object(self):
        slug = self.kwargs.get('slug')
        qs = Course.objects.filter(slug=slug).lectures().owned(self.request.user)
        if qs.exists():
            obj = qs.first()
            if self.request.user.is_authenticated():
                view_event, created = CourseViewEvent.objects.get_or_create(user=self.request.user, course=obj)
                if view_event:
                    view_event.views += 1
                    view_event.save()
            return obj
        return Http404

    def get_context_data(self, *args, **kwargs):
        context = super(CourseDetailView, self).get_context_data(*args, **kwargs)
        return context


class CourseListView(ListView):
    paginate_by = 6

    def get_queryset(self):
        request = self.request
        qs = Course.objects.all()
        query = request.GET.get('q')
        user = self.request.user
        if query:
            qs = qs.filter(title__icontains=query).order_by('-id')
        if user.is_authenticated():
            qs = qs.order_by('-id')
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(CourseListView, self).get_context_data(*args, **kwargs)
        return context




class CourseUpdateView(StaffRequiredMixin, UpdateView):
    queryset = Course.objects.all()
    form_class = CourseForm


class CourseDeleteView(StaffRequiredMixin, DeleteView):
    queryset = Course.objects.all()
    success_url = reverse_lazy('courses:list')


class CoursePurchaseView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, slug=None):
        qs = Course.objects.filter(slug=slug).owned(self.request.user)
        if qs.exists():
            user = self.request.user
            if user.is_authenticated():
                my_courses = user.mycourses
                # run transaction
                # if successful
                my_courses.courses.add(qs.first())
                return qs.first().get_absolute_url()
            return qs.first().get_absolute_url()
        return "/courses/"

courses/templates/courses/course_confirm_delete.html
{% extends 'dashboard/dashboard_base.html' %}
{% block title %} Courses |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-list-ul"></i> Courses</h1>
            <p>Eswahiligigs courses </p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="{% url 'courses:list' %}">Courses</a></li>
            <li class="breadcrumb-item"><a href="{% url 'courses:detail' object.slug %}"> {{ object.title }}</a></li>
            <li class="breadcrumb-item">Delete</li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="row">
                    <div class="col-lg-6">
                        <form method="post" action="">{% csrf_token %}
                            <p>Are you sure you want to delete <b>{{ object.title }}?</b> course</p>
                            <input type="submit" value="Yes" class="btn btn-danger">
                            <a class="btn btn-warning" href="{{ object.get_absolute_url }}">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

courses/templates/courses/course_detail.html
{% extends 'dashboard/dashboard_base.html' %}
{% block title %} Courses |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-edit"></i> Courses Detail</h1>
            <p>ESwahiligigs {{ object.title }} course</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            {% if request.user.is_superuser or request.user.is_staff %}
                <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'courses:list' %}">Courses</a>
                </li>
                <li class="breadcrumb-item"><a class="btn btn-warning" href="{% url 'courses:edit' object.slug %}">Edit
                    This Course</a></li>
                <li class="breadcrumb-item"><a class="btn btn-danger" href="{% url 'courses:delete' object.slug %}">Delete
                    This Course</a></li>
            {% else %}
                <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
                <li class="breadcrumb-item"><a href="{% url 'courses:list' %}">Courses</a></li>
                <li class="breadcrumb-item"><a href=""></a> {{ object.title }}</li>
            {% endif %}
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="row">
                    <div class="col-lg-6">
                        {{ object.title }}
                        {% if object.image %}<img src="{{ object.image.url }}" class="img-fluid" alt="">{% endif %}
                        {{ object.description }}
                        {% if not user.is_subscribed %}
                            {#        {{ object.display_price }}#}
                            <a href="{% url 'payments:checkout' %}">Enroll</a>
                        {% endif %}
                        <div class="row">
                            <div class="col-sm-12">
                                {% for item in object.lecture_set.all %}

                                    <div class="list-group">
                                        <a {% if user.is_subscribed or item.free %}
                                            href="{{ item.get_absolute_url }}" {% endif %}class="list-group-item list-group-item-action lead ">
                                            {{ item.title }}{% if item.free %}
                                                <small>Free Preview</small>{% endif %}
                                        </a>
                                        {% empty %}
                                        <p class="lead"> Lectures coming soon</p>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock content %}

courses/templates/courses/course_form.html
{% extends 'dashboard/dashboard_base.html' %}
{% block title %} Courses |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-graduation-cap"></i> Courses </h1>
            <p>ESwahiligigs </p>
        </div>

        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="{% url 'courses:list' %}"> Courses</a></li>
            <li class="breadcrumb-item">Add or Edit</li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="row">
                    <div class="col-lg-6">
                        <form method="post" action="">{% csrf_token %}
                            {{ form }}

                            {#                            <h3>Lectures</h3>#}
                            {#                           {{ lecture.management_form }}#}
                            {#{% for form in lecture.forms  %}#}
                            {#    {{ form }}#}
                            {##}
                            {#                            {% endfor %}#}


                            <input type="submit" value="Save" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

courses/templates/courses/course_list.html
{% extends 'dashboard/dashboard_base.html' %}
{% load search_form %}
{% block title %} Courses |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-university"></i> Courses</h1>
            <p>Best swahili courses for all users</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item">Courses</li>
        </ul>
    </div>
    {#    {% if request.GET.q %}#}
    {#        <p> You searched for <b>{{ request.GET.q }}</b></p>#}
    {#    {% endif %}#}
    <div class="row">
        <div class="col-md-12">
            <div class="tile">

                <div class="row">
                    <div class="col-md-4 offset-md-3">
                        {% search_form request %}
                    </div>
                </div>

                <div class="row">
                    {% if user.is_subscribed %}
                        {% for item in object_list %}
                            <div class="col-md-4 col-sm-12">
                                {% include 'courses/snippets/course_thumbnail_subscribed_display.html' with course=item user=user %}

                            </div>
                            {% cycle '' '' '</div><div class="row">' %}
                        {% empty %}
                            <p class="lead">No Item Found</p>
                        {% endfor %}
                    {% else %}
                        {% for item in object_list %}
                            <div class="col-md-4 col-sm-12">
                                {% include 'courses/snippets/course_thumbnail_display.html' with course=item user=user %}

                            </div>
                            {% cycle '' '' '</div><div class="row">' %}
                        {% empty %}
                            <p class="lead">No Item Found</p>
                        {% endfor %}
                    {% endif %}

                </div>
                <div class="row">
                    <div class="offset-lg-4">

                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    {% if page_obj.previous_page_number > 1 %}
                                        <li class="page-item"><a class="page-link"
                                                                 href="{% url 'courses:list' %}?page=1">First</a>
                                        </li>
                                    {% endif %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{% url 'courses:list' %}?page={{ page_obj.previous_page_number }} "
                                           aria-label="Previous"><span aria-hidden="true">&laquo;</span>
                                            <span class="sr-only">Previous</span></a>
                                    </li>
                                    {% if page_obj.previous_page_number > 1 %}
                                        <li class="page-item">
                                            <a class="page-link"
                                               href="{% url 'courses:list' %}?page={{ page_obj.previous_page_number }} ">{{ page_obj.previous_page_number }}</a>
                                        </li>
                                    {% endif %}

                                {% endif %}
                                <li class="page-item active"><a class="page-link" href="#"> {{ page_obj.number }}<span
                                        class="sr-only">(current)</span></a>
                                </li>

                                {% if page_obj.has_next %}
                                    {% if page_obj.paginator.num_pages > page_obj.next_page_number %}
                                        <li class="page-item"><a class="page-link"
                                                                 href="{% url 'courses:list' %}?page={{ page_obj.next_page_number }} ">{{ page_obj.next_page_number }}</a>
                                        </li>
                                    {% endif %}
                                    <li class="page-item"><a class="page-link"
                                                             href="{% url 'courses:list' %}?page={{ page_obj.next_page_number }} "
                                                             aria-label="Next"> <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span></a>
                                    </li>
                                    {% if page_obj.paginator.num_pages > page_obj.number %}
                                        <li class="page-item"><a class="page-link"
                                                                 href="{% url 'courses:list' %}?page={{ page_obj.paginator.num_pages }} ">Last</a>
                                        </li>
                                    {% endif %}

                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>


                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
            </div>
        </div>
    </div>


{% endblock content %}

courses/templates/courses/lecture_detail.html
{% extends 'dashboard/dashboard_base.html' %}
{% load render_video %}

{% block title %} Courses |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="row">
                    {{ object.title }}
                    <div class="col-sm-6">
                        {% render_video object.video %}
                        <div class="load_comments" data-url="{{ request.build_absolute_uri }}"
                             data-api-endpoint="/api/comments/"></div>
                    </div>


                </div>
            </div>
        </div>
    </div>
{% endblock content %}

courses/templates/courses/must_purchase.html
{% extends 'base.html' %}
{% block title %} Courses |  {{ block.super }}   {% endblock %}
{% block content %}

   <h3>Purchase  {{ object.title }}</h3>
    {{ object.description }}
    {% if not object.is_owner %}
        {{ object.display_price }}
        <a href="{{ object.get_purchase_url }}">Purchase</a>
    {% endif %}


{% endblock content %}