categories/urls.py
from django.conf.urls import url
from .views import (CategoryListView, CategoryDetailView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView)

urlpatterns = [
    url(r'^$', CategoryListView.as_view(), name='list'),
    url(r'^create/$', CategoryCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', CategoryDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', CategoryUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', CategoryDeleteView.as_view(), name='delete'),

]

eswahiligigs/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from .views import HomePageView, HomeStagePageView, login_after_password_change, MainPageView, DashboardPageView, \
    AccountPageView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePageView.as_view(), name='landing'),
    url(r'^main/$', MainPageView.as_view(), name='main'),
    url(r'^dashboard/account/user/$', AccountPageView.as_view(), name='account_dashboard'),
    url(r'^dashboard/$', DashboardPageView.as_view(), name='dashboard'),
    url(r'^accounts/password/change/$', login_after_password_change,
        name='account_change_password'),
    url('accounts/', include('allauth.urls')),
    url(r'^home/$', HomeStagePageView.as_view(), name='home'),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^videos/', include('videos.urls', namespace='videos')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^payments/', include('billing.urls', namespace='payments')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^api/comments/', include('comments.api.urls', namespace='api_comments')),
    url(r'^eswahiligigs/messages/', include('messages_eswahili.urls', namespace='eswahiligigs_messages')),
    url(r'^questions/', include('questions.urls', namespace='questions')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/urls.py
from django.conf.urls import url
from .views import SearchView

urlpatterns = [
    url(r'^$', SearchView.as_view(), name='default'),

]

categories/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Count
from courses.utils import create_slug
from courses.fields import PositionField
from django.db.models.signals import pre_save, post_save
from videos.models import Video


# Create your models here.
class CategoryQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)


class CategoryManager(models.Manager):
    def get_queryset(self):
        return CategoryQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().all().active().annotate(
            courses_length=Count('secondary_category', distinct=True)).prefetch_related('primary_category',
                                                                                        'secondary_category')


class Category(models.Model):
    title = models.CharField(max_length=120)
    video = models.ForeignKey(Video, null=True, blank=True)
    order = PositionField(blank=True)
    slug = models.SlugField(blank=True)
    active = models.BooleanField(default=True)
    description = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CategoryManager()

    class Meta:
        verbose_name = 'Categories'
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('categories:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


def pre_save_category_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_category_receiver, sender=Category)

categories/forms.py
from django import forms
from .models import Category
from videos.models import Video


class CategoryAdminForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['order','title', 'video', 'description', 'slug']

    def __init__(self, *args, **kwargs):
        super(CategoryAdminForm, self).__init__(*args, **kwargs)
        obj = kwargs.get("instance")
        qs = Video.objects.all().unused()
        if obj:
            if obj.video:
                this_ = Video.objects.filter(pk=obj.video.pk)
                qs = (qs | this_)
            self.fields['video'].queryset = qs
        else:
            self.fields['video'].queryset = qs

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'description', 'active']

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['active'].widget.attrs['class'] = 'form-control'

categories/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView,
                                  DetailView,
                                  ListView,
                                  UpdateView,
                                  DeleteView,
                                  RedirectView)
from .models import Category
from .forms import CategoryForm
from videos.mixins import StaffRequiredMixin


# Create your views here.
# Create your views here.
class CategoryCreateView(StaffRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm


class CategoryListView(ListView):
    queryset = Category.objects.all()


class CategoryDetailView(DetailView):
    queryset = Category.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(*args, **kwargs)
        obj = context.get('object')
        qs1 = obj.primary_category.all().owned(self.request.user)
        qs2 = obj.secondary_category.all().owned(self.request.user)
        qs = (qs1 | qs2).distinct()
        context['featured_courses'] = qs1
        context['courses'] = qs
        return context


class CategoryUpdateView(StaffRequiredMixin, UpdateView):
    queryset = Category.objects.all()
    form_class = CategoryForm


class CategoryDeleteView(StaffRequiredMixin, DeleteView):
    queryset = Category.objects.all()
    success_url = reverse_lazy('categories:list')

categories/templates/categories/category_confirm_delete.html
{% extends 'dashboard/dashboard_base.html' %}
{% block title %} Categories |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-list-ul"></i> Categories</h1>
            <p>Eswahiligigs courses Category</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="{% url 'categories:list' %}">Categories</a></li>
            <li class="breadcrumb-item"><a href="{% url 'categories:detail' object.slug %}"> {{ object.title }}</a></li>
            <li class="breadcrumb-item">Delete</li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="row">
                    <div class="col-lg-6">
                        <form method="post" action="">{% csrf_token %}
                            <p>Are you sure you want to delete <b>{{ object.title }}?</b> Category</p>
                            <input type="submit" value="Yes" class="btn btn-danger">
                            <a class="btn btn-warning" href="{{ object.get_absolute_url }}">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

categories/templates/categories/category_detail.html
{% extends 'dashboard/dashboard_base.html' %}
{% block title %} Categories |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-list-ul"></i> Categories</h1>
            <p>Eswahiligigs courses categories</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            {#            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>#}
            {% if request.user.is_superuser or request.user.is_staff %}
                <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'categories:list' %}">Categories</a>
                </li>
                <li class="breadcrumb-item"><a class="btn btn-warning" href="{% url 'categories:edit' object.slug %}">Edit
                    This Categories</a></li>
                <li class="breadcrumb-item"><a class="btn btn-danger" href="{% url 'categories:delete' object.slug %}">Delete
                    This Category</a></li>
            {% else %}
                <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
                <li class="breadcrumb-item"><a href="{% url 'categories:list' %}">Categories</a></li>
                <li class="breadcrumb-item"><a href=""></a> {{ object.title }}</li>
            {% endif %}


        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">

                <div class="row">
                    {% if user.is_subscribed %}
                        {% for item in featured_courses %}
                            <div class="col-md-3 col-sm-12">
                                {% include 'courses/snippets/course_featured_subscribed_display.html' with course=item %}
                            </div>
                            {% cycle '' '' '</div><div class="row">' %}
                        {% endfor %}
                        {% else %}
                         {% for item in featured_courses %}
                            <div class="col-md-3 col-sm-12">
                                {% include 'courses/snippets/course_featured_thumbnail.html' with course=item %}
                            </div>
                            {% cycle '' '' '</div><div class="row">' %}
                        {% endfor %}

                    {% endif %}
                </div>
                <div class="row">
                    {% if user.is_subscribed %}
                        {% for item in courses %}
                            <div class="col-md-4 col-sm-12">
                                {% include 'courses/snippets/course_thumbnail_subscribed_display.html' with course=item %}
                            </div>
                            {% cycle '' '' '</div><div class="row">' %}
                        {% empty %}
                            <div class="row">
                                <div class="col-lg-12 offset-lg-4">
                                    <p class="lead"> No Courses associated with this Category</p>
                                    <a href="{% url 'categories:list' %}">Go back to Categories</a>
                                </div>
                            </div>

                        {% endfor %}
                    {% else %}
                        {% for item in courses %}
                            <div class="col-md-4 col-sm-12">
                                {% include 'courses/snippets/course_thumbnail_display.html' with course=item %}
                            </div>
                            {% cycle '' '' '</div><div class="row">' %}
                        {% empty %}
                            <div class="row">
                                <div class="col-lg-12 offset-lg-4">
                                    <p class="lead"> No Courses associated with this Category</p>
                                    <a href="{% url 'categories:list' %}">Go back to Categories</a>
                                </div>
                            </div>

                        {% endfor %}
                    {% endif %}


                </div>
            </div>
        </div>
    </div>

{% endblock %}

categories/templates/categories/category_form.html
{% extends 'dashboard/dashboard_base.html' %}
{% block title %} Categories |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-list-ul"></i> Categories</h1>
            <p>Eswahiligigs courses categories</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="{% url 'categories:list' %}">Categories</a></li>
            <li class="breadcrumb-item">Add/Edit</li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="row">
                    <div class="col-lg-6">
                        <form method="post" action="">{% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="Save" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

categories/templates/categories/category_list.html
{% extends 'dashboard/dashboard_base.html' %}
{% block title %} Categories |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-list-ul"></i> Categories</h1>
            <p>Eswahiligigs courses categories</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item">Categories</li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">

                <div class="row">
                    <div class="col-sm-12">
                        <h1>Categories</h1>
                    </div>
                    <div class="col-sm-3">
                        <div class="list-group">
                            {% for item in object_list %}
                                <a href="{{ item.get_absolute_url }}"
                                   class="list-group-item d-flex justify-content-between align-items-center ">
                                    {{ item.title }}
                                    {% if item.courses_length > 0 %}

                                        {% if item.primary_category.all.count > 0 %}
                                            <span class="badge badge-primary  badge-pill">
                                  {{ item.primary_category.all.count }} Featured </span>
                                        {% endif %}
                                        <span class="badge badge-primary badge-pill">{{ item.courses_length }} Course
                                            {% if item.courses_length > 1 %}s {% endif %}</span>

                                    {% endif %}
                                </a>
                                {% if forloop.counter|divisibleby:2 %}
                                    </div></div>
                                    <div class="col-sm-3">
                                    <div class="list-group">
                                {% endif %}
                            {% endfor %}

                            </div>
                            </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}