eswahiligigs/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from .views import HomePageView, HomeStagePageView, login_after_password_change, MainPageView, DashboardPageView, \
    AccountPageView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePageView.as_view(), name='landing'),
    url(r'^main/$', MainPageView.as_view(), name='main'),
    url(r'^dashboard/account/user/$', AccountPageView.as_view(), name='account_dashboard'),
    url(r'^dashboard/$', DashboardPageView.as_view(), name='dashboard'),
    url(r'^accounts/password/change/$', login_after_password_change,
        name='account_change_password'),
    url('accounts/', include('allauth.urls')),
    url(r'^home/$', HomeStagePageView.as_view(), name='home'),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^videos/', include('videos.urls', namespace='videos')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^payments/', include('billing.urls', namespace='payments')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^api/comments/', include('comments.api.urls', namespace='api_comments')),
    url(r'^eswahiligigs/messages/', include('messages_eswahili.urls', namespace='eswahiligigs_messages')),
    url(r'^questions/', include('questions.urls', namespace='questions')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/urls.py
from django.conf.urls import url
from .views import SearchView

urlpatterns = [
    url(r'^$', SearchView.as_view(), name='default'),

]

videos/urls.py
from django.conf.urls import url, include
from .views import VideoListView, VideoDetailView, VideoCreateView, VideoUpdateView, VideoDeleteView

urlpatterns = [

    url(r'^$', VideoListView.as_view(), name='list'),
    url(r'^create/$', VideoCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/$', VideoDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/$', VideoDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', VideoUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', VideoDeleteView.as_view(), name='delete'),
]

videos/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.db.models import Q
from courses.utils import create_slug


# Create your models here.
class VideoQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def unused(self):
        return self.filter(Q(lecture__isnull=True) & Q(category__isnull=True))


class VideoManager(models.Manager):
    def get_queryset(self):
        return VideoQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().all()


class Video(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(blank=True)
    free = models.BooleanField(default=True)
    member_required = models.BooleanField(default=False)
    embed_code = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = VideoManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('videos:detail', kwargs={'slug': self.slug})


def pre_save_video_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_video_receiver, sender=Video)

videos/forms.py
from django import forms
from .models import Video


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'embed_code']

    def __init__(self, *args, **kwargs):
        super(VideoForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['embed_code'].widget.attrs['class'] = 'form-control'


videos/views.py
from django.shortcuts import render
from django.views.generic import (CreateView,
                                  DetailView,
                                  ListView,
                                  UpdateView,
                                  DeleteView)
from .models import Video
from .forms import VideoForm
from .mixins import MemberRequiredMixin, StaffRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy


# Create your views here.
class VideoCreateView(StaffRequiredMixin, CreateView):
    model = Video
    form_class = VideoForm


class VideoDetailView(MemberRequiredMixin, DetailView):
    queryset = Video.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(VideoDetailView, self).get_context_data(*args, **kwargs)
        return context


class VideoListView(ListView):

    def get_queryset(self):
        request = self.request
        qs = Video.objects.all()
        query = request.GET.get('q')
        query_set = Q(title__icontains=query) | Q(title__contains=query)
        if query:
            qs = qs.filter(query_set)
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(VideoListView, self).get_context_data(*args, **kwargs)
        return context


class VideoUpdateView(StaffRequiredMixin, UpdateView):
    queryset = Video.objects.all()
    form_class = VideoForm


class VideoDeleteView(StaffRequiredMixin, DeleteView):
    queryset = Video.objects.all()
    success_url = reverse_lazy('videos:list')

videos/templates/videos/video_confirm_delete.html
{% extends 'dashboard/dashboard_base.html' %}
{% block title %} Videos |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-list-ul"></i> Videos</h1>
            <p>Eswahiligigs courses Videos</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="{% url 'videos:list' %}">Videos</a></li>
            <li class="breadcrumb-item"><a href="{% url 'videos:detail' object.slug %}"> {{ object.title }}</a></li>
            <li class="breadcrumb-item">Delete</li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="row">
                    <div class="col-lg-6">
                        <form method="post" action="">{% csrf_token %}
                            <p>Are you sure you want to delete <b>{{ object.title }}?</b> video</p>
                            <input type="submit" value="Yes" class="btn btn-danger">
                            <a  class="btn btn-warning" href="{{ object.get_absolute_url }}">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

videos/templates/videos/video_detail.html
{% extends 'dashboard/dashboard_base.html' %}
{% load render_video %}
{% block title %} Videos |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-list-ul"></i> Videos</h1>
            <p>Eswahiligigs Videos</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            {#            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>#}
            {% if request.user.is_superuser or request.user.is_staff %}
                <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'videos:list' %}">Videos</a>
                </li>
                <li class="breadcrumb-item"><a class="btn btn-warning" href="{% url 'videos:edit' object.slug %}">Edit
                    This Video</a></li>
                <li class="breadcrumb-item"><a class="btn btn-danger" href="{% url 'videos:delete' object.slug %}">Delete
                    This Video</a></li>
                 {% else %}
                <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
                <li class="breadcrumb-item"><a href="{% url 'videos:list' %}">Videos</a></li>
                <li class="breadcrumb-item"><a href=""></a> {{ object.title }}</li>
            {% endif %}
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="row">
                    <div class="col-sm-6">
                        <h3>{{ object.title }}</h3>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        {% render_video object %}
                        <div class="load_comments" data-url="{{ request.build_absolute_uri }}"
                             data-api-endpoint="/api/comments/"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

videos/templates/videos/video_form.html
{% extends 'dashboard/dashboard_base.html' %}
{% block title %} Videos |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-list-ul"></i> Videos</h1>
            <p>Eswahiligigs courses videos</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="{% url 'videos:list' %}">Videos</a></li>
            <li class="breadcrumb-item">Add/Edit</li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="row">
                    <div class="col-lg-6">
                        <form method="post" action="">{% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="Save" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

videos/templates/videos/video_list.html
{% extends 'dashboard/dashboard_base.html' %}
{% block title %} Videos |  {{ block.super }}   {% endblock %}
{% block content %}
    <div class="app-title">
        <div>
            <h1><i class="fa fa-university"></i> Courses</h1>
            <p>Best swahili courses for all users</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item">Videos</li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="row">
                    <div class="col-sm-12">
                        <h1>Videos</h1>
                    </div>
                    <div class="col-sm-4">
                        <div class="list-group">
                            {% for item in object_list %}
                                <a href="{{ item.get_absolute_url }}"
                                   class="list-group-item d-flex justify-content-between align-items-center ">
                                    {{ item.title }}

                                </a>
                                {% if forloop.counter|divisibleby:2 %}
                                    </div></div>
                                    <div class="col-sm-4">
                                    <div class="list-group">
                                {% endif %}
                            {% endfor %}


                            </div>
                            </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}